name: Test CI

on:
    push:
        branches-ignore:
            - gh-pages
            - browser
    pull_request:
        branches:
            - "*"
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Test
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
            - run: |
                  npm install
                  npm test

